### ISSUE TITLE
Patch for configure.py to work under python 3

### ISSUE THREAD

**Issue by ckaran** [martine/ninja#969] opened 2015-05-08 12:23 UTC
Python 3 removed support for `except foo, e` style for catching exceptions and enforced `except foo as e`.  The following patch seems to work under both python 2 and 3, but I suggest further testing.  I think you can safely ignore the removal of `from __future__ import print_function`; it doesn't seem to affect python 3 one way or the other.

```diff
diff --git a/configure.py b/configure.py
index aac4ad4f0af36cf1689175a922c51b87c01b8cc6..3950670e990c0cd96441d18a8ae74904de44e707 100755
--- a/configure.py
+++ b/configure.py
@@ -19,7 +19,7 @@
 Projects that use ninja themselves should either write a similar script
 or use a meta-build system that supports Ninja output."""
 
-from __future__ import print_function
+
 
 from optparse import OptionParser
 import os
@@ -164,7 +164,7 @@ class Bootstrap:
         """Run a subcommand, quietly.  Prints the full command on error."""
         try:
             subprocess.check_call(cmdline, shell=True)
-        except subprocess.CalledProcessError, e:
+        except subprocess.CalledProcessError as e:
             print('when running: ', cmdline)
             raise
```

**Comment by nicolasdespres** [comment] 2015-05-08 12:41
`from __future__ import print_function` does not affect python3 but is required by python2 to treat `print` as a function instead of a statement. So we must keep it.

**Comment by ckaran** [comment] 2015-05-08 19:40
I'm sorry if my comment was unclear; what I meant was that it had no effect on python 3, so you can keep it or not as needed.  And clearly since you want to continue supporting python 2, it is needed!

Thanks,
Cem Karan

**Comment by nico** [comment] 2015-05-09 19:37
This is fixed on trunk. This is a dupe of #877.

**Comment by nico** [comment] 2015-05-09 19:38
(…but thanks for the patch!)

**Closed by nico** 2015-05-09 19:37 UTC

**Comment by ckaran** [comment] 2015-05-11 14:17
Thank YOU for making ninja!  Definitely makes my life easier...

Thanks,
Cem Karan
