### ISSUE TITLE
restat target as dirty when manifest file is rebuilt

### ISSUE THREAD

**Issue by ukai** [martine/ninja#994] opened 2015-07-27 08:09 UTC
rule regen_ninja
     command = touch build.ninja
     generator = 1
     description = Regenerate ninja files due to dependency
    build build.ninja: regen_ninja envlist
    
    build .always_build: phony
    rule regen_envlist
     command = rm -f $out.tmp && echo ENVTEST=$$ENVTEST >> $out.tmp && (diff $out.tmp $out || mv $out.tmp $out)
     restat = 1
     generator = 1
     description = Check $out
    build envlist: regen_envlist .always_build

This worked in old ninja, but ninja 1.6 fails as
    [1/2] Check envlist
    ....
    [1/2] Check envlist
    ninja: error: manifest 'build.ninja' still dirty after 100 tries

bisect revealed that commit 5fbfa4ba72883cc0ecd199d17a70da3698be0402 is culprit.

**Comment by nico** [comment] 2015-07-27 18:19
This is essentially a dupe of #987 – see there for some discussion and possible workarounds. I agree that something needs to be done here.

**Closed by nico** 2015-07-27 18:19 UTC

**Comment by alankdkd** [comment] 2019-07-31 16:03
I solved the "ninja: error: manifest 'build.ninja' still dirty after 100 tries" problem by locating every build.ninja file in my project, editing it (space then backspace) then saving it.  Buggy software.
