### ISSUE TITLE
Build considered up-to-date when timestamps are too close

### ISSUE THREAD

**Issue by atilaneves** [martine/ninja#915] opened 2015-02-17 14:41 UTC
% ll --time-style=full-iso calc
    -rwxr-xr-x 1 aalvesne wireshark 591K 2015-02-17 15:24:40.448613031 +0000 calc*
    % ll --time-style=full-iso **/constants.d
    -rw-r--r-- 1 aalvesne wireshark 26 2015-02-17 15:24:40.641946373 +0000 leproj/source/constants.d

The timestamps are so close because the files were modified by automated testing. Running ninja (calc depends on constants.o which depends on constants.d) does nothing in this situation, I'm assuming due to second-based granularity. My workaround for now is to sleep 1s in the tests because modifying the files.

**Comment by nico** [comment] 2015-02-17 15:39
Thanks for the report!

This is a dupe of #371.

**Closed by nico** 2015-02-17 15:39 UTC
